extra-package-dbs: []
packages:
- '.'
extra-deps:
- random-extras-0.19
- git: https://github.com/stillinbeta/twitter-types.git
  commit: 63c6de714634c665ef6f34d421a22d101baa3da3
  subdirs:
  - twitter-types
  - twitter-types-lens

resolver: lts-10.5
